=== pakwheels/api-suite-pakwheels/schemas/sifm/lead.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Sell It For Me Lead Response",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "success",
    "error",
    "sell_it_for_me_lead_id",
    "has_credits",
    "product",
    "user_id",
    "mobile",
    "mobile_verified",
    "mobile_uuid"
  ],
  "properties": {
    "success": {
      "type": "string"
    },
    "error": {
      "type": ["string", "null"]
    },
    "sell_it_for_me_lead_id": {
      "type": ["integer", "null"]
    },
    "has_credits": {
      "type": "boolean"
    },
    "product": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "price",
        "type"
      ],
      "properties": {
        "id": {
          "type": ["integer", "null"]
        },
        "name": {
          "type": ["string", "null"]
        },
        "price": {
          "type": ["number", "string", "null"]
        },
        "type": {
          "type": "string"
        }
      }
    },
    "user_id": {
      "type": ["integer", "null"]
    },
    "mobile": {
      "type": "string"
    },
    "mobile_verified": {
      "type": "boolean"
    },
    "mobile_uuid": {
      "type": ["string", "null"]
    }
  }
}

=== pakwheels/api-suite-pakwheels/data/expected_responses/sifm/lead.json
{
  "success": "Thanks for your interest in PakWheels Sell It For Me. Our sales agent will be in touch with you in the next 24 hours and will guide you through the process.",
  "error": null,
  "sell_it_for_me_lead_id": 10530,
  "has_credits": true,
  "product": {
    "id": null,
    "name": null,
    "price": null,
    "type": "sell_it_for_me_lead"
  },
  "user_id": 1702164,
  "mobile": "03234822302",
  "mobile_verified": false,
  "mobile_uuid": "19747a4d2248eeae05eecd104ed389fb"
}
